version: "3.7"

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: employee-manager-server
    container_name: employee-manager-node-server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    restart: always
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo:27017/employee-manager
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-manager-client
    container_name: employee-manager-client-react
    command: npm start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
